export const POST_COMMENT = "POST_COMMENT";
export const ADD_COMMENTS = "ADD_COMMENT";
export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const COMMENTS_LOAD_FAILED = "COMMENTS_LOAD_FAILED"; 

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED"; 
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT"; 